### ISSUE TITLE
Docker compose file

### ISSUE THREAD

**Issue by shawnthompson** [pmmp/PocketMine-Docker#13]
Any thoughts of adding a `docker-compose.yml` to your repo?

```
version: 1.0
services:
  minecraft:
    image: "pmmp/pocketmine-mp"
    container_name: "minecraft"
    restart: always
    ports:
      - 19132:19132/udp
      - 19132:19132/tcp
    volumes:
      - ./minecraft:/data
```

That's what I'm using so far, next is to add the RCON values, the plugin volume might need to be separate too. I'm still learning.
