### ISSUE TITLE
Volumes not being used

### ISSUE THREAD

**Issue by DrSeussFreak** [pmmp/PocketMine-Docker#15]
I am trying to switch from a full-blown ubuntu install to containers, and I cannot get this container to leverage my volumes.  Docker compose is below

```
version: "3"
services:
  pocketmine:
    container_name: pocketmine
    image: pmmp/pocketmine-mp
    restart: unless-stopped
    ports:
      - 19132:19132/udp
      - 19132:19132/tcp
      - 19133:19133/tcp
      - 19133:19133/udp
    volumes:
      - /docker/pocketmine/config:/data
      - /docker/pocketmine/plugins:/plugins
```

No data is in /docker/pocketmine/config and when I put my old config in there, they are not be read.
